import json
from pathlib import Path

LANG = Path(__file__).resolve().parents[1] / "src" / "main" / "resources" / "assets" / "pattern_converter" / "lang"

TRANSLATIONS = {
    "de_de": {
        "block.pattern_converter.pattern_converter": "Muster-Konverter",
        "block.pattern_converter.pattern_converter.tooltip": "Kodiert Autocrafting-Muster zwischen Refined Storage und Applied Energistics um.",
        "itemGroup.pattern_converter.main": "AE2 & RS2 Muster-Konverter",
        "format.pattern_converter.rs2": "Refined Storage",
        "format.pattern_converter.rs2.short": "RS2",
        "format.pattern_converter.ae2": "Applied Energistics",
        "format.pattern_converter.ae2.short": "AE2",
        "direction.pattern_converter.rs_to_ae": "RS2 → AE2",
        "direction.pattern_converter.ae_to_rs": "AE2 → RS2",
        "mode.pattern_converter.auto": "Automatisch",
        "mode.pattern_converter.force_rs_to_ae": "Gesperrt: RS2 → AE2",
        "mode.pattern_converter.force_ae_to_rs": "Gesperrt: AE2 → RS2",
        "shape.pattern_converter.crafting": "Handwerks",
        "shape.pattern_converter.processing": "Verarbeitungs",
        "shape.pattern_converter.stonecutting": "Steinsäge",
        "shape.pattern_converter.smithing": "Schmiede",
        "key_type.pattern_converter.forge_energy": "Forge-Energie",
        "key_type.pattern_converter.ars_source": "Quelle (Source)",
        "key_type.pattern_converter.if_souls": "Seelen",
        "message.pattern_converter.fail.not_a_pattern": "Kein kodiertes Muster",
        "message.pattern_converter.fail.blank_in_input": "Leeres Muster: Leere Muster gehören in den Pufferslot unten",
        "message.pattern_converter.fail.undecodable": "Musterdaten sind ungültig oder verweisen auf fehlende Inhalte",
        "message.pattern_converter.fail.direction_locked": "Richtung ist auf %s gesperrt",
        "message.pattern_converter.fail.translator_disabled": "%s-Muster sind in der Konfiguration deaktiviert",
        "message.pattern_converter.fail.no_encoder": "Kein Kodierer für %s registriert",
        "message.pattern_converter.fail.unmappable_input": "Eingabe %s hat keine Entsprechung in %s",
        "message.pattern_converter.fail.unmappable_output": "Ausgabe %s hat keine Entsprechung in %s",
        "message.pattern_converter.fail.custom_rejected": "%s ist weder Gegenstand noch Flüssigkeit; per Konfiguration abgelehnt",
        "message.pattern_converter.fail.no_outputs_left": "Nach dem Entfernen nicht abbildbarer Ausgaben bliebe keine übrig",
        "message.pattern_converter.fail.too_many_inputs": "Zu viele Eingaben für %s: braucht %s Slots, hat %s",
        "message.pattern_converter.fail.too_many_outputs": "Zu viele Ausgaben für %s: braucht %s Slots, hat %s",
        "message.pattern_converter.fail.recipe_missing": "%s-Rezept für diese Zutaten nicht gefunden",
        "message.pattern_converter.fail.alternatives_rejected": "Alternative Eingaben lassen sich in AE2 nicht abbilden; per Konfiguration abgelehnt",
        "message.pattern_converter.fail.fluid_substitution_rejected": "Flüssigkeitsersetzung lässt sich in RS2 nicht abbilden; per Konfiguration abgelehnt",
        "message.pattern_converter.fail.empty_pattern": "Muster hat keine Eingaben oder keine Ausgaben",
        "message.pattern_converter.fail.fallback_disabled": "Generischer API-Fallback ist in der Konfiguration deaktiviert",
        "message.pattern_converter.fail.unknown_resource": "Unbekannter Ressourcentyp %s auf der %s-Seite (keine Brücke installiert)",
        "message.pattern_converter.warn.alternatives_dropped": "Alternative Eingaben für %s verworfen (AE2-Verarbeitungsmuster erlauben nur eine)",
        "message.pattern_converter.warn.fluid_substitution_dropped": "Flüssigkeitsersetzung verworfen (keine RS2-Entsprechung)",
        "message.pattern_converter.warn.generic_fallback": "%s wurde über die generische Muster-API gelesen und als Verarbeitungsmuster umgewandelt",
        "message.pattern_converter.warn.directions_dropped": "AdvancedAE-Eingaberichtungen verworfen (RS2 leitet nach Provider-Seite)",
        "message.pattern_converter.warn.output_dropped": "Ausgabe %s verworfen (keine %s-Entsprechung)",
        "message.pattern_converter.warn.amount_split": "%s auf %s Slots aufgeteilt (RS2-Slotlimit)",
        "message.pattern_converter.warn.condensed": "Mehrfache %s-Einträge zu einer Menge zusammengefasst",
        "message.pattern_converter.status.idle": "Leerlauf",
        "message.pattern_converter.status.waiting_blank": "Braucht leere %s-Muster im Puffer",
        "message.pattern_converter.status.output_full": "Ausgaberaster ist voll",
        "message.pattern_converter.status.return_full": "Kein Platz für die geleerten %s-Muster",
        "message.pattern_converter.status.queued": "Wartet auf den nächsten Zyklus",
        "message.pattern_converter.status.converted": "%s Muster umgewandelt %s",
        "gui.pattern_converter.direction.auto": "Auto",
        "gui.pattern_converter.direction.locked": "Gesperrt",
        "gui.pattern_converter.direction.none": "Wartet auf Muster",
        "gui.pattern_converter.notes": "Letzte Hinweise:",
        "gui.pattern_converter.arrows.title": "Umwandlungsrichtung",
        "gui.pattern_converter.arrows.desc": "Leuchtender Pfeil = aktuell genutzte Richtung. Jedes Muster wird ins Format des anderen Mods umgewandelt.",
        "gui.pattern_converter.slot.input": "Kodierte RS2- oder AE2-Muster hierher",
        "gui.pattern_converter.slot.output": "Umgewandelte Muster und die geleerten Originale erscheinen hier",
        "gui.pattern_converter.slot.blank_return": "Nur Maschine: geleerte Originale kommen hier als leere Muster zurück",
        "gui.pattern_converter.slot.blank_supply": "Leere Muster des Zielformats (eins pro Umwandlung verbraucht)",
        "gui.pattern_converter.override.title": "Richtung überschreiben",
        "gui.pattern_converter.override.current": "Aktuell: %s",
        "gui.pattern_converter.override.next": "Klick: %s",
        "gui.pattern_converter.issues.title": "Problem melden",
        "gui.pattern_converter.issues.desc": "Öffnet den GitHub-Issue-Tracker des Mods im Browser",
        "jei.pattern_converter.category": "Muster-Umwandlung",
        "emi.category.pattern_converter.conversion": "Muster-Umwandlung",
        "jei.pattern_converter.shapes": "Handwerk, Verarbeitung, Steinsäge und Schmiede",
        "jei.pattern_converter.arrow": "%s → %s",
        "jei.pattern_converter.info.1": "Lege kodierte Muster eines Lagermods zusammen mit leeren Mustern des anderen in das Eingaberaster; der Muster-Konverter kodiert sie über die Muster-API des Zielmods neu. Die geleerten Originale kommen als leere Muster zurück.",
        "jei.pattern_converter.info.2": "Die Richtung wird pro Muster erkannt; der ⇕-Knopf sperrt sie. Nach jedem Zyklus mit Umwandlung folgt ein Redstone-Impuls; ein Komparator liest das Ausgaberaster.",
        "jei.pattern_converter.info.3": "Muster, die sich auf der anderen Seite nicht abbilden lassen (z. B. Energieressourcen ohne passendes Addon oder mehr Ausgaben, als AE2 erlaubt), werden mit Begründung im GUI abgelehnt.",
        "jei.pattern_converter.info.addons": "Aktive Addon-Kompatibilität: %s",
        "jei.pattern_converter.info.no_addons": "keine installiert",
    },
    "fr_fr": {
        "block.pattern_converter.pattern_converter": "Convertisseur de motifs",
        "block.pattern_converter.pattern_converter.tooltip": "Ré-encode les motifs d'autocraft entre Refined Storage et Applied Energistics.",
        "itemGroup.pattern_converter.main": "AE2 & RS2 Convertisseur de motifs",
        "format.pattern_converter.rs2": "Refined Storage",
        "format.pattern_converter.rs2.short": "RS2",
        "format.pattern_converter.ae2": "Applied Energistics",
        "format.pattern_converter.ae2.short": "AE2",
        "direction.pattern_converter.rs_to_ae": "RS2 → AE2",
        "direction.pattern_converter.ae_to_rs": "AE2 → RS2",
        "mode.pattern_converter.auto": "Automatique",
        "mode.pattern_converter.force_rs_to_ae": "Verrouillé : RS2 → AE2",
        "mode.pattern_converter.force_ae_to_rs": "Verrouillé : AE2 → RS2",
        "shape.pattern_converter.crafting": "de fabrication",
        "shape.pattern_converter.processing": "de traitement",
        "shape.pattern_converter.stonecutting": "de tailleur de pierre",
        "shape.pattern_converter.smithing": "de forge",
        "key_type.pattern_converter.forge_energy": "Énergie Forge",
        "key_type.pattern_converter.ars_source": "Source",
        "key_type.pattern_converter.if_souls": "Âmes",
        "message.pattern_converter.fail.not_a_pattern": "Ce n'est pas un motif encodé",
        "message.pattern_converter.fail.blank_in_input": "Motif vierge : placez les vierges dans l'emplacement tampon en dessous",
        "message.pattern_converter.fail.undecodable": "Les données du motif sont invalides ou référencent du contenu manquant",
        "message.pattern_converter.fail.direction_locked": "Direction verrouillée sur %s",
        "message.pattern_converter.fail.translator_disabled": "Les motifs %s sont désactivés dans la configuration",
        "message.pattern_converter.fail.no_encoder": "Aucun encodeur enregistré pour %s",
        "message.pattern_converter.fail.unmappable_input": "L'entrée %s n'a pas d'équivalent dans %s",
        "message.pattern_converter.fail.unmappable_output": "La sortie %s n'a pas d'équivalent dans %s",
        "message.pattern_converter.fail.custom_rejected": "%s n'est ni un objet ni un fluide ; refusé par la configuration",
        "message.pattern_converter.fail.no_outputs_left": "Aucune sortie ne resterait après suppression de celles sans équivalent",
        "message.pattern_converter.fail.too_many_inputs": "Trop d'entrées pour %s : %s emplacements nécessaires, %s disponibles",
        "message.pattern_converter.fail.too_many_outputs": "Trop de sorties pour %s : %s emplacements nécessaires, %s disponibles",
        "message.pattern_converter.fail.recipe_missing": "Recette %s introuvable pour ces ingrédients",
        "message.pattern_converter.fail.alternatives_rejected": "Les entrées alternatives ne peuvent pas s'exprimer dans AE2 ; refusé par la configuration",
        "message.pattern_converter.fail.fluid_substitution_rejected": "La substitution de fluides ne peut pas s'exprimer dans RS2 ; refusé par la configuration",
        "message.pattern_converter.fail.empty_pattern": "Le motif n'a pas d'entrées ou pas de sorties",
        "message.pattern_converter.fail.fallback_disabled": "Le repli API générique est désactivé dans la configuration",
        "message.pattern_converter.fail.unknown_resource": "Type de ressource %s inconnu côté %s (aucun pont installé)",
        "message.pattern_converter.warn.alternatives_dropped": "Entrées alternatives de %s abandonnées (AE2 n'en accepte qu'une)",
        "message.pattern_converter.warn.fluid_substitution_dropped": "Indicateur de substitution de fluides abandonné (pas d'équivalent RS2)",
        "message.pattern_converter.warn.generic_fallback": "%s a été lu via l'API générique et converti en motif de traitement",
        "message.pattern_converter.warn.directions_dropped": "Directions d'entrée AdvancedAE abandonnées (RS2 route par face du fournisseur)",
        "message.pattern_converter.warn.output_dropped": "Sortie %s abandonnée (pas d'équivalent %s)",
        "message.pattern_converter.warn.amount_split": "%s réparti sur %s emplacements (limite par emplacement RS2)",
        "message.pattern_converter.warn.condensed": "Entrées %s répétées fusionnées en une seule quantité",
        "message.pattern_converter.status.idle": "Inactif",
        "message.pattern_converter.status.waiting_blank": "Nécessite des motifs vierges %s dans le tampon",
        "message.pattern_converter.status.output_full": "Grille de sortie pleine",
        "message.pattern_converter.status.return_full": "Pas de place pour les motifs %s vidés",
        "message.pattern_converter.status.queued": "En attente du prochain cycle",
        "message.pattern_converter.status.converted": "%s motif(s) converti(s) %s",
        "gui.pattern_converter.direction.auto": "Auto",
        "gui.pattern_converter.direction.locked": "Verrouillé",
        "gui.pattern_converter.direction.none": "En attente de motifs",
        "gui.pattern_converter.notes": "Notes récentes :",
        "gui.pattern_converter.arrows.title": "Direction de conversion",
        "gui.pattern_converter.arrows.desc": "Flèche allumée = direction en cours. Chaque motif est converti vers le format de l'autre mod.",
        "gui.pattern_converter.slot.input": "Motifs RS2 ou AE2 encodés ici",
        "gui.pattern_converter.slot.output": "Les motifs convertis et les originaux vidés apparaissent ici",
        "gui.pattern_converter.slot.blank_return": "Réservé à la machine : les originaux vidés reviennent ici en motifs vierges",
        "gui.pattern_converter.slot.blank_supply": "Motifs vierges du format de destination (un consommé par conversion)",
        "gui.pattern_converter.override.title": "Forcer la direction",
        "gui.pattern_converter.override.current": "Actuel : %s",
        "gui.pattern_converter.override.next": "Clic : %s",
        "gui.pattern_converter.issues.title": "Signaler un problème",
        "gui.pattern_converter.issues.desc": "Ouvre le suivi des problèmes GitHub du mod dans votre navigateur",
        "jei.pattern_converter.category": "Conversion de motifs",
        "emi.category.pattern_converter.conversion": "Conversion de motifs",
        "jei.pattern_converter.shapes": "Fabrication, traitement, tailleur de pierre et forge",
        "jei.pattern_converter.arrow": "%s → %s",
        "jei.pattern_converter.info.1": "Placez des motifs encodés de l'un des mods de stockage dans la grille d'entrée avec des motifs vierges de l'autre ; le convertisseur les ré-encode via l'API de motifs du mod cible. Les originaux vidés reviennent en vierges.",
        "jei.pattern_converter.info.2": "La direction est détectée par motif ; le bouton ⇕ la verrouille. Une impulsion de redstone suit chaque cycle ayant converti quelque chose, et un comparateur lit la grille de sortie.",
        "jei.pattern_converter.info.3": "Les motifs sans représentation de l'autre côté (ressources d'énergie sans addon correspondant, plus de sorties qu'AE2 n'en permet…) sont refusés avec la raison affichée dans l'interface.",
        "jei.pattern_converter.info.addons": "Compatibilité addon active : %s",
        "jei.pattern_converter.info.no_addons": "aucun installé",
    },
    "es_es": {
        "block.pattern_converter.pattern_converter": "Conversor de patrones",
        "block.pattern_converter.pattern_converter.tooltip": "Recodifica patrones de autofabricación entre Refined Storage y Applied Energistics.",
        "itemGroup.pattern_converter.main": "AE2 & RS2 Conversor de patrones",
        "format.pattern_converter.rs2": "Refined Storage",
        "format.pattern_converter.rs2.short": "RS2",
        "format.pattern_converter.ae2": "Applied Energistics",
        "format.pattern_converter.ae2.short": "AE2",
        "direction.pattern_converter.rs_to_ae": "RS2 → AE2",
        "direction.pattern_converter.ae_to_rs": "AE2 → RS2",
        "mode.pattern_converter.auto": "Automático",
        "mode.pattern_converter.force_rs_to_ae": "Bloqueado: RS2 → AE2",
        "mode.pattern_converter.force_ae_to_rs": "Bloqueado: AE2 → RS2",
        "shape.pattern_converter.crafting": "de fabricación",
        "shape.pattern_converter.processing": "de procesado",
        "shape.pattern_converter.stonecutting": "de cortapiedras",
        "shape.pattern_converter.smithing": "de herrería",
        "key_type.pattern_converter.forge_energy": "Energía Forge",
        "key_type.pattern_converter.ars_source": "Source",
        "key_type.pattern_converter.if_souls": "Almas",
        "message.pattern_converter.fail.not_a_pattern": "No es un patrón codificado",
        "message.pattern_converter.fail.blank_in_input": "Patrón en blanco: colócalos en la ranura de reserva de abajo",
        "message.pattern_converter.fail.undecodable": "Los datos del patrón no son válidos o apuntan a contenido inexistente",
        "message.pattern_converter.fail.direction_locked": "Dirección bloqueada en %s",
        "message.pattern_converter.fail.translator_disabled": "Los patrones de %s están desactivados en la configuración",
        "message.pattern_converter.fail.no_encoder": "No hay codificador registrado para %s",
        "message.pattern_converter.fail.unmappable_input": "La entrada %s no tiene equivalente en %s",
        "message.pattern_converter.fail.unmappable_output": "La salida %s no tiene equivalente en %s",
        "message.pattern_converter.fail.custom_rejected": "%s no es un objeto ni un fluido; rechazado por la configuración",
        "message.pattern_converter.fail.no_outputs_left": "No quedaría ninguna salida tras descartar las que no se pueden representar",
        "message.pattern_converter.fail.too_many_inputs": "Demasiadas entradas para %s: necesita %s ranuras, hay %s",
        "message.pattern_converter.fail.too_many_outputs": "Demasiadas salidas para %s: necesita %s ranuras, hay %s",
        "message.pattern_converter.fail.recipe_missing": "No se encontró una receta %s para estos ingredientes",
        "message.pattern_converter.fail.alternatives_rejected": "Las entradas alternativas no se pueden expresar en AE2; rechazado por la configuración",
        "message.pattern_converter.fail.fluid_substitution_rejected": "La sustitución de fluidos no se puede expresar en RS2; rechazado por la configuración",
        "message.pattern_converter.fail.empty_pattern": "El patrón no tiene entradas o no tiene salidas",
        "message.pattern_converter.fail.fallback_disabled": "El respaldo genérico por API está desactivado en la configuración",
        "message.pattern_converter.fail.unknown_resource": "Tipo de recurso %s desconocido en el lado de %s (sin puente instalado)",
        "message.pattern_converter.warn.alternatives_dropped": "Entradas alternativas de %s descartadas (AE2 solo admite una)",
        "message.pattern_converter.warn.fluid_substitution_dropped": "Marca de sustitución de fluidos descartada (sin equivalente en RS2)",
        "message.pattern_converter.warn.generic_fallback": "%s se leyó mediante la API genérica y se convirtió como patrón de procesado",
        "message.pattern_converter.warn.directions_dropped": "Direcciones de entrada de AdvancedAE descartadas (RS2 enruta por la cara del proveedor)",
        "message.pattern_converter.warn.output_dropped": "Salida %s descartada (sin equivalente en %s)",
        "message.pattern_converter.warn.amount_split": "%s repartido en %s ranuras (límite por ranura de RS2)",
        "message.pattern_converter.warn.condensed": "Entradas repetidas de %s fusionadas en una cantidad",
        "message.pattern_converter.status.idle": "Inactivo",
        "message.pattern_converter.status.waiting_blank": "Necesita patrones en blanco de %s en la reserva",
        "message.pattern_converter.status.output_full": "La cuadrícula de salida está llena",
        "message.pattern_converter.status.return_full": "No hay sitio para los patrones %s vaciados",
        "message.pattern_converter.status.queued": "En cola para el siguiente ciclo",
        "message.pattern_converter.status.converted": "%s patrón(es) convertido(s) %s",
        "gui.pattern_converter.direction.auto": "Auto",
        "gui.pattern_converter.direction.locked": "Bloqueado",
        "gui.pattern_converter.direction.none": "Esperando patrones",
        "gui.pattern_converter.notes": "Notas recientes:",
        "gui.pattern_converter.arrows.title": "Dirección de conversión",
        "gui.pattern_converter.arrows.desc": "Flecha iluminada = dirección en uso. Cada patrón se convierte al formato del otro mod.",
        "gui.pattern_converter.slot.input": "Patrones codificados de RS2 o AE2 aquí",
        "gui.pattern_converter.slot.output": "Aquí aparecen los patrones convertidos y los originales vaciados",
        "gui.pattern_converter.slot.blank_return": "Solo la máquina: los originales vaciados vuelven aquí como patrones en blanco",
        "gui.pattern_converter.slot.blank_supply": "Patrones en blanco del formato de destino (uno por conversión)",
        "gui.pattern_converter.override.title": "Forzar dirección",
        "gui.pattern_converter.override.current": "Actual: %s",
        "gui.pattern_converter.override.next": "Clic: %s",
        "gui.pattern_converter.issues.title": "Informar de un problema",
        "gui.pattern_converter.issues.desc": "Abre el rastreador de incidencias de GitHub del mod en tu navegador",
        "jei.pattern_converter.category": "Conversión de patrones",
        "emi.category.pattern_converter.conversion": "Conversión de patrones",
        "jei.pattern_converter.shapes": "Fabricación, procesado, cortapiedras y herrería",
        "jei.pattern_converter.arrow": "%s → %s",
        "jei.pattern_converter.info.1": "Coloca patrones codificados de cualquiera de los dos mods de almacenamiento en la cuadrícula de entrada junto con patrones en blanco del otro; el conversor los recodifica mediante la API de patrones del mod destino. Los originales vaciados vuelven como patrones en blanco.",
        "jei.pattern_converter.info.2": "La dirección se detecta por patrón; el botón ⇕ la bloquea. Tras cada ciclo que convierte algo se emite un pulso de redstone, y un comparador lee la cuadrícula de salida.",
        "jei.pattern_converter.info.3": "Los patrones que no se pueden representar en el otro lado (recursos de energía sin un addon compatible, más salidas de las que AE2 permite…) se rechazan mostrando el motivo en la interfaz.",
        "jei.pattern_converter.info.addons": "Compatibilidad con addons activa: %s",
        "jei.pattern_converter.info.no_addons": "ninguno instalado",
    },
    "pt_br": {
        "block.pattern_converter.pattern_converter": "Conversor de Padrões",
        "block.pattern_converter.pattern_converter.tooltip": "Recodifica padrões de autocrafting entre Refined Storage e Applied Energistics.",
        "itemGroup.pattern_converter.main": "AE2 & RS2 Conversor de Padrões",
        "format.pattern_converter.rs2": "Refined Storage",
        "format.pattern_converter.rs2.short": "RS2",
        "format.pattern_converter.ae2": "Applied Energistics",
        "format.pattern_converter.ae2.short": "AE2",
        "direction.pattern_converter.rs_to_ae": "RS2 → AE2",
        "direction.pattern_converter.ae_to_rs": "AE2 → RS2",
        "mode.pattern_converter.auto": "Automático",
        "mode.pattern_converter.force_rs_to_ae": "Travado: RS2 → AE2",
        "mode.pattern_converter.force_ae_to_rs": "Travado: AE2 → RS2",
        "shape.pattern_converter.crafting": "de fabricação",
        "shape.pattern_converter.processing": "de processamento",
        "shape.pattern_converter.stonecutting": "de cortador de pedra",
        "shape.pattern_converter.smithing": "de ferraria",
        "key_type.pattern_converter.forge_energy": "Energia Forge",
        "key_type.pattern_converter.ars_source": "Source",
        "key_type.pattern_converter.if_souls": "Almas",
        "message.pattern_converter.fail.not_a_pattern": "Não é um padrão codificado",
        "message.pattern_converter.fail.blank_in_input": "Padrão em branco: coloque-os no espaço de reserva abaixo",
        "message.pattern_converter.fail.undecodable": "Os dados do padrão são inválidos ou apontam para conteúdo ausente",
        "message.pattern_converter.fail.direction_locked": "Direção travada em %s",
        "message.pattern_converter.fail.translator_disabled": "Padrões de %s estão desativados na configuração",
        "message.pattern_converter.fail.no_encoder": "Nenhum codificador registrado para %s",
        "message.pattern_converter.fail.unmappable_input": "A entrada %s não tem equivalente em %s",
        "message.pattern_converter.fail.unmappable_output": "A saída %s não tem equivalente em %s",
        "message.pattern_converter.fail.custom_rejected": "%s não é item nem fluido; rejeitado pela configuração",
        "message.pattern_converter.fail.no_outputs_left": "Nenhuma saída restaria após descartar as sem equivalente",
        "message.pattern_converter.fail.too_many_inputs": "Entradas demais para %s: precisa de %s espaços, há %s",
        "message.pattern_converter.fail.too_many_outputs": "Saídas demais para %s: precisa de %s espaços, há %s",
        "message.pattern_converter.fail.recipe_missing": "Receita %s não encontrada para estes ingredientes",
        "message.pattern_converter.fail.alternatives_rejected": "Entradas alternativas não podem ser expressas no AE2; rejeitado pela configuração",
        "message.pattern_converter.fail.fluid_substitution_rejected": "Substituição de fluidos não pode ser expressa no RS2; rejeitado pela configuração",
        "message.pattern_converter.fail.empty_pattern": "O padrão não tem entradas ou não tem saídas",
        "message.pattern_converter.fail.fallback_disabled": "O fallback genérico por API está desativado na configuração",
        "message.pattern_converter.fail.unknown_resource": "Tipo de recurso %s desconhecido no lado do %s (nenhuma ponte instalada)",
        "message.pattern_converter.warn.alternatives_dropped": "Entradas alternativas de %s descartadas (padrões de processamento do AE2 aceitam só uma)",
        "message.pattern_converter.warn.fluid_substitution_dropped": "Marcação de substituição de fluidos descartada (sem equivalente no RS2)",
        "message.pattern_converter.warn.generic_fallback": "%s foi lido pela API genérica e convertido como padrão de processamento",
        "message.pattern_converter.warn.directions_dropped": "Direções de entrada do AdvancedAE descartadas (o RS2 roteia pela face do provedor)",
        "message.pattern_converter.warn.output_dropped": "Saída %s descartada (sem equivalente em %s)",
        "message.pattern_converter.warn.amount_split": "%s dividido em %s espaços (limite por espaço do RS2)",
        "message.pattern_converter.warn.condensed": "Entradas repetidas de %s unidas em uma única quantidade",
        "message.pattern_converter.status.idle": "Ocioso",
        "message.pattern_converter.status.waiting_blank": "Precisa de padrões em branco de %s na reserva",
        "message.pattern_converter.status.output_full": "A grade de saída está cheia",
        "message.pattern_converter.status.return_full": "Sem espaço para os padrões %s esvaziados",
        "message.pattern_converter.status.queued": "Na fila para o próximo ciclo",
        "message.pattern_converter.status.converted": "%s padrão(ões) convertido(s) %s",
        "gui.pattern_converter.direction.auto": "Auto",
        "gui.pattern_converter.direction.locked": "Travado",
        "gui.pattern_converter.direction.none": "Aguardando padrões",
        "gui.pattern_converter.notes": "Notas recentes:",
        "gui.pattern_converter.arrows.title": "Direção da conversão",
        "gui.pattern_converter.arrows.desc": "Seta acesa = direção em uso. Cada padrão é convertido para o formato do outro mod.",
        "gui.pattern_converter.slot.input": "Padrões codificados de RS2 ou AE2 aqui",
        "gui.pattern_converter.slot.output": "Padrões convertidos e os originais esvaziados aparecem aqui",
        "gui.pattern_converter.slot.blank_return": "Somente a máquina: os originais esvaziados voltam aqui como padrões em branco",
        "gui.pattern_converter.slot.blank_supply": "Padrões em branco do formato de destino (um consumido por conversão)",
        "gui.pattern_converter.override.title": "Forçar direção",
        "gui.pattern_converter.override.current": "Atual: %s",
        "gui.pattern_converter.override.next": "Clique: %s",
        "gui.pattern_converter.issues.title": "Relatar um problema",
        "gui.pattern_converter.issues.desc": "Abre o rastreador de problemas do mod no GitHub no seu navegador",
        "jei.pattern_converter.category": "Conversão de Padrões",
        "emi.category.pattern_converter.conversion": "Conversão de Padrões",
        "jei.pattern_converter.shapes": "Fabricação, processamento, cortador de pedra e ferraria",
        "jei.pattern_converter.arrow": "%s → %s",
        "jei.pattern_converter.info.1": "Coloque padrões codificados de qualquer um dos mods de armazenamento na grade de entrada junto com padrões em branco do outro; o Conversor de Padrões os recodifica pela API de padrões do mod de destino. Os originais esvaziados voltam como padrões em branco.",
        "jei.pattern_converter.info.2": "A direção é detectada por padrão; o botão ⇕ a trava. Um pulso de redstone é emitido após cada ciclo que converteu algo, e um comparador lê a grade de saída.",
        "jei.pattern_converter.info.3": "Padrões que não podem ser representados do outro lado (recursos de energia sem addon correspondente, mais saídas do que o AE2 permite…) são recusados com o motivo exibido na interface.",
        "jei.pattern_converter.info.addons": "Compatibilidade com addons ativa: %s",
        "jei.pattern_converter.info.no_addons": "nenhum instalado",
    },
    "ru_ru": {
        "block.pattern_converter.pattern_converter": "Конвертер шаблонов",
        "block.pattern_converter.pattern_converter.tooltip": "Перекодирует шаблоны автокрафта между Refined Storage и Applied Energistics.",
        "itemGroup.pattern_converter.main": "AE2 & RS2 Конвертер шаблонов",
        "format.pattern_converter.rs2": "Refined Storage",
        "format.pattern_converter.rs2.short": "RS2",
        "format.pattern_converter.ae2": "Applied Energistics",
        "format.pattern_converter.ae2.short": "AE2",
        "direction.pattern_converter.rs_to_ae": "RS2 → AE2",
        "direction.pattern_converter.ae_to_rs": "AE2 → RS2",
        "mode.pattern_converter.auto": "Автоматически",
        "mode.pattern_converter.force_rs_to_ae": "Закреплено: RS2 → AE2",
        "mode.pattern_converter.force_ae_to_rs": "Закреплено: AE2 → RS2",
        "shape.pattern_converter.crafting": "крафта",
        "shape.pattern_converter.processing": "обработки",
        "shape.pattern_converter.stonecutting": "камнереза",
        "shape.pattern_converter.smithing": "кузнечного стола",
        "key_type.pattern_converter.forge_energy": "Энергия Forge",
        "key_type.pattern_converter.ars_source": "Источник (Source)",
        "key_type.pattern_converter.if_souls": "Души",
        "message.pattern_converter.fail.not_a_pattern": "Это не закодированный шаблон",
        "message.pattern_converter.fail.blank_in_input": "Пустой шаблон: кладите пустые шаблоны в буферный слот ниже",
        "message.pattern_converter.fail.undecodable": "Данные шаблона повреждены или ссылаются на отсутствующее содержимое",
        "message.pattern_converter.fail.direction_locked": "Направление закреплено: %s",
        "message.pattern_converter.fail.translator_disabled": "Шаблоны %s отключены в конфигурации",
        "message.pattern_converter.fail.no_encoder": "Нет кодировщика для %s",
        "message.pattern_converter.fail.unmappable_input": "У входа %s нет эквивалента в %s",
        "message.pattern_converter.fail.unmappable_output": "У выхода %s нет эквивалента в %s",
        "message.pattern_converter.fail.custom_rejected": "%s — не предмет и не жидкость; отклонено конфигурацией",
        "message.pattern_converter.fail.no_outputs_left": "После удаления непереносимых выходов не осталось бы ни одного",
        "message.pattern_converter.fail.too_many_inputs": "Слишком много входов для %s: нужно %s слотов, есть %s",
        "message.pattern_converter.fail.too_many_outputs": "Слишком много выходов для %s: нужно %s слотов, есть %s",
        "message.pattern_converter.fail.recipe_missing": "Рецепт %s для этих ингредиентов не найден",
        "message.pattern_converter.fail.alternatives_rejected": "Альтернативные входы нельзя выразить в AE2; отклонено конфигурацией",
        "message.pattern_converter.fail.fluid_substitution_rejected": "Замену жидкостей нельзя выразить в RS2; отклонено конфигурацией",
        "message.pattern_converter.fail.empty_pattern": "У шаблона нет входов или выходов",
        "message.pattern_converter.fail.fallback_disabled": "Универсальный API-резерв отключён в конфигурации",
        "message.pattern_converter.fail.unknown_resource": "Неизвестный тип ресурса %s на стороне %s (мост не установлен)",
        "message.pattern_converter.warn.alternatives_dropped": "Альтернативные входы для %s отброшены (в AE2 допускается один)",
        "message.pattern_converter.warn.fluid_substitution_dropped": "Флаг замены жидкостей отброшен (в RS2 нет эквивалента)",
        "message.pattern_converter.warn.generic_fallback": "%s прочитан через универсальный API и преобразован как шаблон обработки",
        "message.pattern_converter.warn.directions_dropped": "Направления входов AdvancedAE отброшены (RS2 маршрутизирует по стороне провайдера)",
        "message.pattern_converter.warn.output_dropped": "Выход %s отброшен (нет эквивалента в %s)",
        "message.pattern_converter.warn.amount_split": "%s разделён на %s слотов (лимит слота RS2)",
        "message.pattern_converter.warn.condensed": "Повторяющиеся записи %s объединены в одно количество",
        "message.pattern_converter.status.idle": "Простой",
        "message.pattern_converter.status.waiting_blank": "Нужны пустые шаблоны %s в буфере",
        "message.pattern_converter.status.output_full": "Выходная сетка заполнена",
        "message.pattern_converter.status.return_full": "Нет места для очищенных шаблонов %s",
        "message.pattern_converter.status.queued": "В очереди на следующий цикл",
        "message.pattern_converter.status.converted": "Преобразовано шаблонов: %s (%s)",
        "gui.pattern_converter.direction.auto": "Авто",
        "gui.pattern_converter.direction.locked": "Закреплено",
        "gui.pattern_converter.direction.none": "Ожидание шаблонов",
        "gui.pattern_converter.notes": "Последние заметки:",
        "gui.pattern_converter.arrows.title": "Направление преобразования",
        "gui.pattern_converter.arrows.desc": "Горящая стрелка — используемое направление. Каждый шаблон преобразуется в формат другого мода.",
        "gui.pattern_converter.slot.input": "Сюда — закодированные шаблоны RS2 или AE2",
        "gui.pattern_converter.slot.output": "Здесь появляются преобразованные шаблоны и очищенные оригиналы",
        "gui.pattern_converter.slot.blank_return": "Только для машины: очищенные оригиналы возвращаются сюда пустыми шаблонами",
        "gui.pattern_converter.slot.blank_supply": "Пустые шаблоны целевого формата (по одному на преобразование)",
        "gui.pattern_converter.override.title": "Принудительное направление",
        "gui.pattern_converter.override.current": "Сейчас: %s",
        "gui.pattern_converter.override.next": "Клик: %s",
        "gui.pattern_converter.issues.title": "Сообщить о проблеме",
        "gui.pattern_converter.issues.desc": "Открывает трекер проблем мода на GitHub в браузере",
        "jei.pattern_converter.category": "Преобразование шаблонов",
        "emi.category.pattern_converter.conversion": "Преобразование шаблонов",
        "jei.pattern_converter.shapes": "Крафт, обработка, камнерез и кузнечный стол",
        "jei.pattern_converter.arrow": "%s → %s",
        "jei.pattern_converter.info.1": "Положите закодированные шаблоны одного мода хранения во входную сетку вместе с пустыми шаблонами другого — конвертер перекодирует их через API шаблонов целевого мода. Очищенные оригиналы возвращаются пустыми шаблонами.",
        "jei.pattern_converter.info.2": "Направление определяется для каждого шаблона; кнопка ⇕ закрепляет его. После каждого цикла с преобразованием выдаётся импульс редстоуна, компаратор читает выходную сетку.",
        "jei.pattern_converter.info.3": "Шаблоны, которые нельзя представить на другой стороне (энергоресурсы без подходящего аддона, больше выходов, чем допускает AE2…), отклоняются с указанием причины в интерфейсе.",
        "jei.pattern_converter.info.addons": "Активная совместимость с аддонами: %s",
        "jei.pattern_converter.info.no_addons": "ничего не установлено",
    },
    "zh_cn": {
        "block.pattern_converter.pattern_converter": "样板转换器",
        "block.pattern_converter.pattern_converter.tooltip": "在精致存储与应用能源之间重新编码自动合成样板。",
        "itemGroup.pattern_converter.main": "AE2 & RS2 样板转换器",
        "format.pattern_converter.rs2": "精致存储",
        "format.pattern_converter.rs2.short": "RS2",
        "format.pattern_converter.ae2": "应用能源",
        "format.pattern_converter.ae2.short": "AE2",
        "direction.pattern_converter.rs_to_ae": "RS2 → AE2",
        "direction.pattern_converter.ae_to_rs": "AE2 → RS2",
        "mode.pattern_converter.auto": "自动",
        "mode.pattern_converter.force_rs_to_ae": "锁定：RS2 → AE2",
        "mode.pattern_converter.force_ae_to_rs": "锁定：AE2 → RS2",
        "shape.pattern_converter.crafting": "合成",
        "shape.pattern_converter.processing": "处理",
        "shape.pattern_converter.stonecutting": "切石",
        "shape.pattern_converter.smithing": "锻造",
        "key_type.pattern_converter.forge_energy": "Forge 能量",
        "key_type.pattern_converter.ars_source": "魔源",
        "key_type.pattern_converter.if_souls": "灵魂",
        "message.pattern_converter.fail.not_a_pattern": "不是已编码的样板",
        "message.pattern_converter.fail.blank_in_input": "空白样板：请放入下方的缓冲槽",
        "message.pattern_converter.fail.undecodable": "样板数据无效或引用了缺失的内容",
        "message.pattern_converter.fail.direction_locked": "方向已锁定为 %s",
        "message.pattern_converter.fail.translator_disabled": "%s 样板已在配置中禁用",
        "message.pattern_converter.fail.no_encoder": "未注册 %s 的编码器",
        "message.pattern_converter.fail.unmappable_input": "输入 %s 在 %s 中没有对应项",
        "message.pattern_converter.fail.unmappable_output": "输出 %s 在 %s 中没有对应项",
        "message.pattern_converter.fail.custom_rejected": "%s 既不是物品也不是流体；已被配置拒绝",
        "message.pattern_converter.fail.no_outputs_left": "丢弃无法映射的输出后将没有任何输出",
        "message.pattern_converter.fail.too_many_inputs": "%s 的输入过多：需要 %s 个槽位，只有 %s 个",
        "message.pattern_converter.fail.too_many_outputs": "%s 的输出过多：需要 %s 个槽位，只有 %s 个",
        "message.pattern_converter.fail.recipe_missing": "未找到这些材料的%s配方",
        "message.pattern_converter.fail.alternatives_rejected": "AE2 无法表达备选输入；已被配置拒绝",
        "message.pattern_converter.fail.fluid_substitution_rejected": "RS2 无法表达流体替代；已被配置拒绝",
        "message.pattern_converter.fail.empty_pattern": "样板没有输入或没有输出",
        "message.pattern_converter.fail.fallback_disabled": "通用 API 回退已在配置中禁用",
        "message.pattern_converter.fail.unknown_resource": "%s 侧存在未知的资源类型 %s（未安装桥接）",
        "message.pattern_converter.warn.alternatives_dropped": "已丢弃 %s 的备选输入（AE2 处理样板只允许一种）",
        "message.pattern_converter.warn.fluid_substitution_dropped": "已丢弃流体替代标记（RS2 无对应项）",
        "message.pattern_converter.warn.generic_fallback": "%s 通过通用样板 API 读取，并按处理样板转换",
        "message.pattern_converter.warn.directions_dropped": "已丢弃 AdvancedAE 的输入方向（RS2 按供应器朝向路由）",
        "message.pattern_converter.warn.output_dropped": "已丢弃输出 %s（%s 无对应项）",
        "message.pattern_converter.warn.amount_split": "%s 已拆分到 %s 个槽位（RS2 单槽上限）",
        "message.pattern_converter.warn.condensed": "重复的 %s 条目已合并为一个数量",
        "message.pattern_converter.status.idle": "空闲",
        "message.pattern_converter.status.waiting_blank": "缓冲槽需要 %s 空白样板",
        "message.pattern_converter.status.output_full": "输出格已满",
        "message.pattern_converter.status.return_full": "没有空间存放清空的 %s 样板",
        "message.pattern_converter.status.queued": "等待下一周期",
        "message.pattern_converter.status.converted": "已转换 %s 个样板 %s",
        "gui.pattern_converter.direction.auto": "自动",
        "gui.pattern_converter.direction.locked": "已锁定",
        "gui.pattern_converter.direction.none": "等待样板",
        "gui.pattern_converter.notes": "最近提示：",
        "gui.pattern_converter.arrows.title": "转换方向",
        "gui.pattern_converter.arrows.desc": "亮起的箭头 = 当前使用的方向。每个样板都会转换为另一个模组的格式。",
        "gui.pattern_converter.slot.input": "在此放入已编码的 RS2 或 AE2 样板",
        "gui.pattern_converter.slot.output": "转换后的样板和清空的原样板会出现在这里",
        "gui.pattern_converter.slot.blank_return": "仅限机器：清空的原样板会以空白样板返回这里",
        "gui.pattern_converter.slot.blank_supply": "目标格式的空白样板（每次转换消耗一个）",
        "gui.pattern_converter.override.title": "方向覆盖",
        "gui.pattern_converter.override.current": "当前：%s",
        "gui.pattern_converter.override.next": "点击：%s",
        "gui.pattern_converter.issues.title": "报告问题",
        "gui.pattern_converter.issues.desc": "在浏览器中打开本模组的 GitHub 问题追踪页",
        "jei.pattern_converter.category": "样板转换",
        "emi.category.pattern_converter.conversion": "样板转换",
        "jei.pattern_converter.shapes": "合成、处理、切石与锻造",
        "jei.pattern_converter.arrow": "%s → %s",
        "jei.pattern_converter.info.1": "将任一存储模组的已编码样板与另一模组的空白样板一起放入输入格，样板转换器会通过目标模组自身的样板 API 重新编码。清空的原样板会以空白样板返回。",
        "jei.pattern_converter.info.2": "方向按样板自动检测；⇕ 按钮可锁定方向。每个完成转换的周期后会发出红石脉冲，比较器可读取输出格。",
        "jei.pattern_converter.info.3": "无法在另一侧表示的样板（例如没有对应附属的能量资源，或输出数超过 AE2 上限）会被拒绝，并在界面中显示原因。",
        "jei.pattern_converter.info.addons": "已启用的附属兼容：%s",
        "jei.pattern_converter.info.no_addons": "未安装",
    },
}


def main():
    en = json.loads((LANG / "en_us.json").read_text(encoding="utf-8"))
    for locale, table in TRANSLATIONS.items():
        missing = [k for k in en if k not in table]
        extra = [k for k in table if k not in en]
        if missing or extra:
            raise SystemExit(f"{locale}: missing {missing} extra {extra}")
        ordered = {k: table[k] for k in en}
        (LANG / f"{locale}.json").write_text(json.dumps(ordered, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        print(f"{locale}: {len(ordered)} keys")


if __name__ == "__main__":
    main()
